function init()
  m.poster = m.top.findNode("poster")
  ' m.theLabel = m.top.findNode("theLabel")
end function

function itemContentChanged()
  ' m.theLabel.text = "C" + m.top.itemContent.title
  m.poster.uri = m.top.itemContent.HDGRIDPOSTERURL
end function

function currTargetChanged()
  if m.top.index = 0
    print "currTarget for item "; m.top.index; " changed to "; m.top.currTarget
  end if
end function

