import "pkg:/source/roku_modules/maestro/ml/ListMixin.brs"
import "pkg:/source/roku_modules/maestro/ml/BaseRow.brs"
import "pkg:/source/roku_modules/maestro/ml/RowItemScroller.brs"
import "pkg:/source/roku_modules/maestro/ml/RowItemViewManager.brs"
import "pkg:/source/roku_modules/maestro/ml/ItemFocusManager.brs"


@node("DateHeaderRow", "ml_BaseRow")
class DateHeaderRow extends ml.BaseRow

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Public Fields
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  public focusedCellIndex = 0

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Views
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  private menu

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Callbacks
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  private function onMenuItemChange(index as integer)
    m.log.info("selected tab item", index)
    if index = 0
      m.sendRowData({ offset: -1 })
    else if index = 1
      m.sendRowData({ offset: 1 })
    end if
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Overridden Methods
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  protected override function createViews()
    bundle = m.styleManager@.loadBundle("pkg:/source/rows/DateHeaderRow.bundle")
    m.createViewsFromStyleJson(bundle.views)
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Row Delegate Methods
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  private function onDidGainFocus(event as ml.ListEvent)
    ' ? "CR: onDidGainFocus " ; " " ; direction
    if m.owner.isFocused or m.owner.isChildFocused
      m.setFocus(m.menu)
    end if
  end function

end class
